type Query {
  user: User
}

type User {
  _id: String
  emails: [Email]
  profile: Profile
}

type Email {
  address: String
  verified: Boolean
}

type Profile {
    screen: String
}

query getCurrentUser {
  user {
    profile {
      screen
    }
    _id
  }
}



