type Query {
  user: User
}

type User {
  _id: String
  emails: [Email]
  profile: Profile
}

type Email {
  address: String
  verified: Boolean
}

type Profile {
    screen: String
}

# type Student implements User {
#     _id: String
#     emails: [Email]
#     profile: Profile
#     studentId: String
# }

# type Instructor implements User {
#     _id: String
#     emails: [Email]
#     profile: Profile
#     instructorId: String
# }

# type Class {
#     _id: String
#     start: Int!
#     end: Int!
#     instructor: Instructor
#     students: [Student]
# }




