dependencies:
  - name: mongodb-replicaset
    version: 1.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
    import-values:
      - mongodb-replicaset
  - name: prometheus
    version: 3.0.2
    repository: https://kubernetes-charts.storage.googleapis.com
    import-values:
      - prometheus
  - name: grafana
    version: 0.3.6
    repository: https://kubernetes-charts.storage.googleapis.com
    import-values:
      - grafana
