dependencies:
  - name: mongodb-replicaset
    version: 1.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: prometheus
    version: 3.0.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: grafana
    version: 0.3.6
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: 0.6.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kube-lego
    version: 0.1.4
    repository: https://kubernetes-charts.storage.googleapis.com
