# Default values for k8s-deployment.
replicaCount: 1
image:
  repository: redacademy/meteor-container
  tag: v0.0.3
  pullPolicy: Always

service:
  name: meteor-deploy-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/_health"
  externalPort: 80
  internalPort: 8080
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/proxy-read-timeout: 3600
    ingress.kubernetes.io/proxy-send-timeout: 3600
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts: 
    - meteor.mackenziekieran.com
  tls:
    - secretName: kube-lego-tls-secret
      hosts:
        - meteor.mackenziekieran.com

appUrl: http://meteor.mackenziekieran.com
  
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

kube-lego:
  config:
    LEGO_EMAIL: mackenzie@redacademy.com  
    LEGO_SECRET_NAME: kube-lego-tls-secret
    LEGO_URL: https://acme-v01.api.letsencrypt.org

grafana:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts: 
        - grafana.mackenziekieran.com


prometheus:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts: 
        - prometheus.mackenziekieran.com
    
