# Default values for k8s-deployment.
replicaCount: 1
image:
  repository: redacademy/meteor-container
  tag: v0.0.3
  pullPolicy: Always

appUrl: http://meteor.mackenziekieran.com

service:
  name: meteor-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/_health"
  externalPort: 80
  internalPort: 8080
  type: NodePort

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/proxy-read-timeout: 3600
    ingress.kubernetes.io/proxy-send-timeout: 3600
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/use-http2: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  hosts: 
    - meteor.mackenziekieran.com
  tls:
    - secretName: meteor-tls-secret
      hosts:
      - meteor.mackenziekieran.com
      

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

kube-lego:
  config:
    LEGO_EMAIL: "remember.mackenzie@gmail.com"
    LEGO_URL: "https://acme-v01.api.letsencrypt.org/directory"

grafana:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts: 
        - grafana.mackenziekieran.com

prometheus:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts: 
        - prometheus.mackenziekieran.com
    
