# Default values for k8s-deployment.
replicaCount: 1
image:
  repository: redacademy/meteor-container
  tag: latest
  pullPolicy: Always

service:
  name: meteor-deploy-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "_health"
  externalPort: 80
  internalPort: 8080
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    # kubernetes.io/tls-acme: "true"
  hosts: 
    - meteor.test.com
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
  
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

grafana:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts: 
        - grafana.test.com

prometheus:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts: 
        - prometheus.test.com
    
