apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        name:  {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PORT
          value: "{{ .Values.service.internalPort }}"
        - name: ROOT_URL
          value: "http://192.168.99.100"
        - name: MONGO_URL
          value: "mongodb://{{ .Release.Name }}-mongodb-replicaset:27017/meteordb?replicaSet=rs0"
        - name: MONGO_OPLOG_URL
          value: "mongodb://{{ .Release.Name }}-mongodb-replicaset:27017/local?authSource=database&replicaSet=rs0"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
