---
kind: Service
apiVersion: v1
metadata:
  name: meteor-deploy-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: meteor
  sessionAffinity: ClientIP
  type: LoadBalancer

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: meteor-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: meteor
        name: meteor
    spec:
      containers:
      - name: meteor
        image: redacademy/meteor-container
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: ROOT_URL
          value: http://192.168.99.100
        - name: MONGO_URL
          value: mongodb://meteor-mongodb-replicaset:27017/meteordb?replicaSet=rs0
        - name: MONGO_OPLOG_URL
          value: mongodb://meteor-mongodb-replicaset:27017/local?authSource=database&replicaSet=rs0