dependencies:
  - name: meteor-mongodb-replicaset
    version: 1.1.0
    repository: https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset
  - name: meteor-prometheus
    version: 3.0.2
    repository: https://github.com/kubernetes/charts/tree/master/stable/prometheus
  - name: meteor-graphana
    version: 0.3.6
    repository: https://github.com/kubernetes/charts/tree/master/stable/grafana
